version: '3.9'

services:
  flask-website:
    image: firasbt/ml-website-flask:latest
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  vscode:
    image: firasbt/vscode-python:latest
    deploy:
      replicas: 0  # This ensures no container is started by default

networks:
  default:
    driver: bridge